spring:
  application:
    name: babyshop
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        prepareThreshold: 0
        preferQueryMode: simple
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: ${JWT_SECRET}
